export default {
	'app.title': 'Príklad aplikácie',
	'app.description': 'Tento príklad slúži na pochopenie lokalizácie.',
	'change_language': 'Změnit jazyk',
	'recentgames': 'Nedávné hry',
	'recentreviews': 'Nedávné recenze',
	'start': 'Začít hru',
	'home': 'Domů',
	'about': 'O hře',
	'play': 'Hrát',
	'matches': 'Hry',
	'reviews': 'Recenze',
	'login': 'Přihlášení',
	'welcome': 'Vítejte',
	'tie': 'Remíza',
	'winner': 'Vítěz',
	'nextplayer': 'Další hráč',
	'cs': 'Čeština',
	'ago': 'před',
	'en': 'Angličtina',
	'signin': 'Přihlásit',
	'signup': 'Registrovat',
	'password': 'Heslo',
	'mhistory': 'Historie zápasů',
	'signout': 'Odhlásit'
};
