export default {
	'app.title': 'Example application',
	'app.description': 'This example is used to understand localization.',
	'change_language': 'Change language',
	'recentgames': 'Recent games',
	'recentreviews': 'Recent reviews',
	'start': 'Lets Start',
	'home': 'Home',
	'play': 'Play',
	'about': 'About',
	'matches': 'Matches',
	'reviews': 'Reviews',
	'login': 'Login',
	'welcome': 'Welcome',
	'nextplayer': 'Next player',
	'tie': 'Tie',
	'winner': 'Winner',
	'cs': 'Czech',
	'en': 'English',
	'ago': 'ago',
	'signin': 'Sign In',
	'signup': 'Sign Up',
	'password': 'Password',
	'mhistory': 'Matches history',
	'signout': 'Sign Out'
};
